CREATE TABLE IF NOT EXISTS configuration_versions (version BIGINT PRIMARY KEY, body JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS source_summaries (name TEXT PRIMARY KEY, address TEXT NOT NULL, offset_ns BIGINT NOT NULL, delay_ns BIGINT NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS leap_second_metadata (version BIGINT PRIMARY KEY, digest TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS state_history (id BIGSERIAL PRIMARY KEY, state TEXT NOT NULL, reason TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
